version: 2.1

.directory: &directory
  working_directory: ~/workspace

jobs:
  checkout-code:
    <<: *directory
    docker:
      - image: cimg/node:14
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace

  bundle-dependencies:
    <<: *directory
    docker:
      - image: cimg/node:14
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - workspace

  lint:
    <<: *directory
    docker:
      - image: cimg/node:14
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: 'Run yarn lint'
          command: yarn lint

  e2e:
    <<: *directory
    docker:
      - image: cimg/node:14
      - image: mariadb:10.9.4
        environment:
          MARIADB_ROOT_PASSWORD: root
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Waiting for Mariadb
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: 'Run E2E Tests'
          command: yarn e2e

  unit:
    <<: *directory
    docker:
      - image: cimg/node:14
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: 'Run Unit Tests'
          command: yarn run test

workflows:
  pipeline:
    jobs:
      - checkout-code
      - bundle-dependencies:
          requires:
            - checkout-code
      - lint:
          requires:
            - bundle-dependencies
      - e2e:
          requires:
            - bundle-dependencies
      - unit:
          requires:
            - bundle-dependencies
